id: 893888a0daa5477a821789baea264490
initial_creation_type: ocr
source_metadata:
  volumes:
    504a3176bcdd4fcfbd0d0353bbe85d93:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: མན་ངག་སྐུའི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
